databases:
  - name: agripulse-db
    plan: free
    databaseName: agripulse
    user: agripulse

services:
  - type: web
    name: agripulse-weather-monitoring-system
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    preDeployCommand: php artisan migrate --force
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: APP_NAME
        value: AgriPulse
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: agripulse-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: BROADCAST_CONNECTION
        value: log
      - key: FILESYSTEM_DISK
        value: local
      - key: MAIL_MAILER
        value: log
